//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q2TabletsInformation
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineDetails_032
    {
        public int MedicineID { get; set; }
        public string MedicineName { get; set; }
        public string Type { get; set; }
        public Nullable<int> BatchNo { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<System.DateTime> ManufactureDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<double> Price { get; set; }
    }
}
